apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: postgres14
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - image: postgres:14-alpine
          name: postgres14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: sasa
            - name: POSTGRES_DB
              value: db-ms-docker-kube
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          persistentVolumeClaim:
            claimName: postgres-pvc