apiVersion: v1
kind: Service
metadata:
  labels:
    app: ms-cursos-server
  name: ms-cursos-server
spec:
  ports:
    - port: 8002
      protocol: TCP
      targetPort: 8002
  selector:
    app: ms-usuarios-server
  type: LoadBalancer