#version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sasa
      MYSQL_DATABASE: db-ms-docker-kube
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring
  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: sasa
      POSTGRES_DB: db-ms-docker-kube
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  ms-usuarios-server:
    container_name: ms-usuarios-server
    build:
      context: ./
      dockerfile: ./ms-usuarios-server/Dockerfile
    image: i-usuarios
    ports:
      - "8001:8001"
    env_file: ./ms-usuarios-server/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  ms-cursos-server:
    container_name: ms-cursos-server
    build:
      context: ./
      dockerfile: ./ms-cursos-server/Dockerfile
    image: i-cursos
    ports:
      - "8002:8002"
    env_file:
      - ./ms-cursos-server/.env
    networks:
      - spring
    depends_on:
      - postgres14
      - ms-usuarios-server
    restart: always
    
volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
networks:
  spring:
    name: spring
    external: true