apiVersion: v1
kind: Secret
metadata:
  name: ms-usuarios-server
type: Opaque
data:
  username: cm9vdA==
  password: c2FzYQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: ms-cursos-server
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: c2FzYQ==